# Generated by Django 2.1.5 on 2019-02-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbrsh_pgm_id', models.CharField(max_length=1)),
                ('mcht_no', models.CharField(max_length=8)),
                ('mcht_nm', models.CharField(max_length=40)),
                ('biz_no', models.CharField(max_length=10)),
                ('mcht_fg', models.CharField(max_length=1)),
                ('crdt_sts', models.CharField(max_length=20)),
                ('cpn_clos_dy', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'MCT_MASTER_MST',
            },
        ),
    ]
